
spring:
  application:
    name: spring-data-demo-1
  datasource:
    url: ## url goes here
    password: ## password
    username: ## username
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
server:
  port: 8080


logging:
  level:
    root: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.web: TRACE
#    edu.miu.cs.cs544.controller: DEBUG

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days